# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('plan', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
