# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0002_auto_20170426_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='travelplans',
            name='users',
            field=models.ManyToManyField(related_name='travelplans', to='pythonapp.User'),
        ),
    ]
