# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0003_auto_20170427_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleGoing',
        ),
    ]
