# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0004_delete_peoplegoing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonapp.TravelPlans')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonapp.User')),
            ],
        ),
    ]
